global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fileWatcher'
    static_configs:
      - targets: ['localhost:9091']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'file_write_events_total|file_remove_events_total|file_create_events_total'
        action: keep
